/**
 * Created by Administrator on 2018/2/24.
 */
const LocalKeys = {
  EXPIRES: "EXPIRES",
  TOKEN: 'TOKEN',
  ACCOUNT: "ACCOUNT"
};
const SessionKeys = {
  AUTHORIZED: 'AUTHORIZED',
  TOKEN: 'TOKEN',
  ACCOUNT: 'ACCOUNT',
  PERMISSION: 'PERMISSION',
  ORGANIZATION: 'ORGANIZATION',
  ORGANIZATIONS: 'ORGANIZATIONS',
  IMC: 'IMC',
  PROJECT: 'PROJECT',
  MONITORITEM1: 'MONITORITEM1',
  MONITORITEM2: 'MONITORITEM2',
  PROJECTIDSEXISTMAP: 'PROJECTIDSEXISTMAP',//已上传项目图的项目id列表
  TEMPINFO: 'TEMPINFO',
  SITUATION: 'SITUATION'
};
export default {LocalKeys, SessionKeys};
